### ISSUE TITLE
Error while parsing Oracle july 2020 cpu advisory

### ISSUE THREAD

**Issue by pedrohc** [mprpic/advisory-parser#22]
URL: https://www.oracle.com/security-alerts/cpujul2020.html

Traceback (most recent call last):
  File "/usr/bin/sfm2", line 11, in <module>
    load_entry_point('sfm2client==2.22.1', 'console_scripts', 'sfm2')()
  File "/usr/lib/python3.7/site-packages/sfm2client/cli/main.py", line 32, in main
    app.run()
  File "/usr/lib/python3.7/site-packages/sfm2client/cli/app.py", line 94, in run
    self.invoke(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/smclip/commands.py", line 330, in invoke
    rv = command.invoke(sub_args)  # Subcommand invocation
  File "/usr/lib/python3.7/site-packages/smclip/commands.py", line 330, in invoke
    rv = command.invoke(sub_args)  # Subcommand invocation
  File "/usr/lib/python3.7/site-packages/smclip/commands.py", line 140, in invoke
    return self.invoke_callbacks(parsed_args)
  File "/usr/lib/python3.7/site-packages/smclip/commands.py", line 155, in invoke_callbacks
    rv = self.this_action(**action_args)
  File "/usr/lib/python3.7/site-packages/sfm2client/cli/flaw.py", line 833, in this_action
    flaws, warnings = AdvisoryParser.parse_from_url(advisory_url)
  File "/usr/lib/python3.7/site-packages/advisory_parser/parser.py", line 33, in parse_from_url
    return parse_mysql_advisory(url)
  File "/usr/lib/python3.7/site-packages/advisory_parser/parsers/mysql.py", line 118, in parse_mysql_advisory
    description, cvss_text = re.split(r'\n\s*CVSS v3', description)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by thoger** [comment]
The minimal fix should be to change the regex used for `re.split()` to `r'\n\s*CVSS v?3'`, i.e. making the `v` character optional.  I used a less minimal fix in #24 to make the pattern more strict and reduce the risk of matching 'CVSS 3' text elsewhere in the description.
